language: node_js
node_js:
- '6'
cache:
  yarn: true
  directories:
  - node_modules
before_install:
- npm config set spin false
- npm install -g npm@^5
script:
- yarn test-ci
- yarn build
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: "l2+oOAYATpgulRB5IDmo4X7BVyeB3woD4w2N+oEtK2ubTBzaVifUJ8+ZXjKmm+SlaGbFo6s6q7NxJONIRXw/4NGp8skHcXfdcCJnAm8k28WD1QjONzLZHSxvbtOFnnqHV5/bIHc7zsQ8ERBArHg25cpLhijSbIQRXy9pFD/NAdAG7ih87iufeYqMwh/2AngujzYMKiIILdFALwmigIERZTufzjX0+uMEMwUB0bmBsyqVvBajn7/WE+9JSqYLhrBrOdM8S+22vsOAmQ4j4iLlSnpLNGKOjOQ0u3VNMfdT+MoXgvLwwcOhgpmgGVIdcDqSxndEOc4S+WvG/H5RLOQBNJtfz//wEp4iX0qr2cDXa9dw/OqA9avSuwhlySbi2ILbkj5N0oH7OKp24GGE0lmueKzO/nZSeMz5WGj33aNJUpL0vmchmOO5SVI+DkoLkcyV5gP0VN+kVNlvBYx+vg1NEwFpnGIT6z6xzUFVxBpOXk9TygeeCC9CGM25zzGNLyVTTUTP8vq1bKc88DaDFNjdSlVWDERiqCQFt/Q+FrkhyweXqDkE8dr/vlp+Nx3j484LZ41UD6stgUnqbzu65VeRCCPtSmQHPyIwpeWHGdLAmNTW1Zr/YVjaiNlXSxaAEd9L0XwcyD5Nc+pQYIcamDiDoxcnA6ZnSwnAWeiTbWpijeo="
  file:
    - build/_output/adverb-clause-roulette.wigt
    - build/_output/adverb-clause-roulette-build-info.yml
  on:
    tags: true
    repo: ucfopen/adverbial-clause-roulette-materia-widget
notifications:
  email: false
  slack:
    secure: "QUM4VltA9aTPdDrYg7R+8bA9bgw6wZCTAik4F59PGVqTETn6dGR7nTH/XrfCs8J0+jh8FNukLDPgkyGoBH8j3pxpu7FeJ8kqSHXT2AayaD70T0nfDJ6czAbvFYfKcKYQpauZL0v4InhCQPh3uytAd23OVnksID7oB0YRW6zWWU3xe2fQ4U4o5EvYPDDwtOwhEPA6yiuB3BWvZ5vNjeWrnIARQEu4TPXQEYnOcTLMVC66lPmcveeWhX0aGRvM5CRewFgW2jt2LOaL+J+CnBmmtqFt7zkaKOeS3uZzwmixMH1pb25qNcnKvwB1RGsO4jGm4hD4YlXD5x6sg6HeIDm/013GXcrYeIxSUpjksrElKa0b3/dlV+b8P9+eY3Hs6cj8RFpH63PHsZIbmTNya48tbt0PU5KvGXrlhiEHCwrUfrSYRL7QWqm6GRbCVBMm+1nN1QnRM+Warm/SlWiwRpKk/Jt1itEkUZVmJfPkclo5Pf7VW8+xlKCTiDj59oNst3SQtPWB9A4GWZ2a+K3ZmCYHwaaGK8A4pPfiUnKGdWZgT7ahy1k6dv2QmbGnvjRj0t14Nz0y5CTTo8IxB67e4Yf29WC9rQfklaN7txKEc3KHleCVYQaEooS3JrYfKEVDilo8t8Ea86afNAKPzM6L7R97lJuzTbkQi2JaSF3lidmR1Zo="

